In [11]:
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
from scipy.io import loadmat

In [27]:
year_start = 1901
year_end = 2014

month_start = 6
month_end = 9

load_data = loadmat('../../Code2/raindat0_25_deg.mat')
total_latlist = load_data['latlist']
total_lonlist = load_data['lonlist']
datmat = np.moveaxis(load_data['hrrainmat'], (0, 1), (1, 0))

num_days_in_month = np.array([30, 31, 30, 31, 31, 30, 31, 30])
cumsum_days = np.cumsum(num_days_in_month, axis=0)
cumsum_days = np.concatenate((np.array([0]), cumsum_days))

day_start_index = cumsum_days[month_start - 4] 
day_end_index = cumsum_days[month_end - 4 + 1]

In [28]:
day_start_index

61

In [29]:
day_end_index

183

In [23]:
cumsum_days

array([  0,  30,  61,  91, 122, 153, 183, 214, 244])

In [9]:
ds = xr.tutorial.load_dataset("air_temperature")
ds

<xarray.Dataset>
Dimensions:  (lat: 25, time: 2920, lon: 53)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Data variables:
    air      (time, lat, lon) float32 241.2 242.5 243.5 ... 296.5 296.2 295.7
Attributes:
    Conventions:  COARDS
    title:        4x daily NMC reanalysis (1948)
    description:  Data is from NMC initialized reanalysis\n(4x/day).  These a...
    platform:     Model
    references:   http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanaly...

In [17]:
ds["air"]

<xarray.DataArray 'air' (time: 2920, lat: 25, lon: 53)>
array([[[241.2    , 242.5    , 243.5    , ..., 232.79999, 235.5    ,
         238.59999],
        [243.79999, 244.5    , 244.7    , ..., 232.79999, 235.29999,
         239.29999],
        [250.     , 249.79999, 248.89   , ..., 233.2    , 236.39   ,
         241.7    ],
        ...,
        [296.6    , 296.19998, 296.4    , ..., 295.4    , 295.1    ,
         294.69998],
        [295.9    , 296.19998, 296.79   , ..., 295.9    , 295.9    ,
         295.19998],
        [296.29   , 296.79   , 297.1    , ..., 296.9    , 296.79   ,
         296.6    ]],

       [[242.09999, 242.7    , 243.09999, ..., 232.     , 233.59999,
         235.79999],
        [243.59999, 244.09999, 244.2    , ..., 231.     , 232.5    ,
         235.7    ],
        [253.2    , 252.89   , 252.09999, ..., 230.79999, 233.39   ,
         238.5    ],
...
        [293.69   , 293.88998, 295.38998, ..., 295.09   , 294.69   ,
         294.29   ],
        [296.29   , 297.19   , 297.59   , ..., 295.29   , 295.09   ,
         294.38998],
        [297.79   , 298.38998, 298.49   , ..., 295.69   , 295.49   ,
         295.19   ]],

       [[245.09   , 244.29   , 243.29   , ..., 241.68999, 241.48999,
         241.79   ],
        [249.89   , 249.29   , 248.39   , ..., 239.59   , 240.29   ,
         241.68999],
        [262.99   , 262.19   , 261.38998, ..., 239.89   , 242.59   ,
         246.29   ],
        ...,
        [293.79   , 293.69   , 295.09   , ..., 295.29   , 295.09   ,
         294.69   ],
        [296.09   , 296.88998, 297.19   , ..., 295.69   , 295.69   ,
         295.19   ],
        [297.69   , 298.09   , 298.09   , ..., 296.49   , 296.19   ,
         295.69   ]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Attributes:
    long_name:     4xDaily Air temperature at sigma level 995
    units:         degK
    precision:     2
    GRIB_id:       11
    GRIB_name:     TMP
    var_desc:      Air temperature
    dataset:       NMC Reanalysis
    level_desc:    Surface
    statistic:     Individual Obs
    parent_stat:   Other
    actual_range:  [185.16 322.1 ]

In [19]:
ds.air.dims

('time', 'lat', 'lon')

In [20]:
ds.air.coords

Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00

In [36]:
data_1 = pd.read_csv('beta_overall_1901-1950_20clus_50years_50op_rs.dat',
                     sep='\s+',header=None)
data_2 = pd.read_csv('overall_locations_analysis/beta_overall_1901-195050years_intesection_ovverall.dat',
                     sep='\s+',header=None)

In [40]:
beta_op = data_1.iloc[0][0:-1].values
beta_ov = data_2.iloc[0][0:-1].values

In [72]:
beta_ov.shape

(1005,)

In [60]:
loc_1 = pd.read_csv('output_1901-1950_50years_20clus_50op_rs.dat',sep='\s+',header=None).values
loc_2 = pd.read_csv('intersection_overall.dat',sep='\s+',header=None).values

In [67]:
loc1 = np.asarray(loc_1[:,0:-7].reshape(1,-1),dtype='int32') - 1
loc2 = np.asarray(loc_2.reshape(1,-1),dtype='int32') - 1

In [68]:
loc2.shape

(1, 1005)

In [85]:
lon_list_1 = total_latlist[loc1].reshape(1000)
lat_list_1 = total_lonlist[loc1].reshape(1000)

lon_list_2 = total_latlist[loc2].reshape(1005)
lat_list_2 = total_lonlist[loc2].reshape(1005)

In [79]:
lon_list_1.shape

(1000,)

In [88]:
dr1 = xr.DataArray(beta_op,dims=("op"),coords={"op":loc1.reshape(-1)})

In [89]:
dr1

<xarray.DataArray (op: 1000)>
array([1.1505e-03, 1.1251e-03, 5.8906e-04, 3.4773e-04, 1.4673e-03,
       7.4942e-30, 3.1061e-30, 1.5284e-30, 7.2484e-05, 3.0413e-03,
       2.2469e-03, 1.6008e-03, 8.4195e-04, 9.3457e-04, 1.6658e-03,
       2.2757e-03, 1.2421e-03, 1.1154e-03, 2.9499e-03, 0.0000e+00,
       2.6180e-03, 4.3387e-30, 1.3876e-03, 1.6008e-03, 1.3124e-03,
       0.0000e+00, 1.1152e-04, 3.8703e-30, 0.0000e+00, 1.2548e-03,
       5.1029e-30, 3.0634e-03, 1.8195e-03, 1.4681e-03, 0.0000e+00,
       7.8886e-30, 1.5540e-03, 0.0000e+00, 0.0000e+00, 1.1833e-30,
       5.9257e-04, 6.4095e-31, 7.7866e-04, 7.0534e-04, 1.5777e-28,
       3.2147e-04, 3.3639e-03, 5.5307e-06, 1.2819e-29, 4.4373e-31,
       1.8800e-03, 6.2047e-03, 1.2353e-03, 1.3698e-03, 7.9093e-04,
       5.8918e-30, 2.2017e-04, 0.0000e+00, 9.0019e-04, 0.0000e+00,
       1.0958e-03, 2.5144e-03, 8.4534e-04, 4.8364e-04, 3.7865e-29,
       2.5877e-03, 1.4606e-03, 4.0676e-30, 7.7055e-04, 4.5606e-30,
       1.4913e-03, 5.8467e-03, 0.0000e+00, 5.0901e-04, 0.0000e+00,
       2.8511e-03, 8.9923e-04, 0.0000e+00, 4.4236e-03, 0.0000e+00,
       3.5745e-30, 3.1517e-04, 4.7386e-03, 1.6008e-03, 1.3651e-03,
       8.7268e-30, 2.2642e-03, 0.0000e+00, 9.7173e-04, 1.8242e-30,
       0.0000e+00, 1.6008e-03, 3.7224e-30, 1.4139e-03, 7.6582e-05,
       4.3634e-30, 1.5493e-03, 0.0000e+00, 0.0000e+00, 0.0000e+00,
...
       9.1390e-04, 7.6072e-04, 5.7657e-04, 3.2137e-05, 4.0901e-03,
       4.2882e-03, 7.5924e-04, 5.6638e-04, 0.0000e+00, 0.0000e+00,
       1.0365e-04, 2.3511e-04, 2.5141e-04, 3.4460e-04, 0.0000e+00,
       0.0000e+00, 1.5716e-03, 4.9239e-04, 4.6480e-04, 0.0000e+00,
       4.3141e-30, 0.0000e+00, 7.6774e-04, 1.3805e-30, 3.4143e-04,
       1.1549e-03, 7.7693e-04, 9.9372e-29, 0.0000e+00, 1.8242e-30,
       4.2131e-03, 1.7208e-03, 1.9722e-30, 4.8817e-03, 1.2552e-03,
       0.0000e+00, 1.4970e-03, 7.9389e-04, 2.0105e-03, 0.0000e+00,
       0.0000e+00, 1.3381e-03, 6.4833e-04, 1.4774e-03, 1.9722e-31,
       1.5777e-30, 5.8643e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       3.1554e-30, 2.7185e-03, 9.2194e-04, 2.1225e-03, 2.7728e-04,
       7.8886e-31, 1.7061e-03, 5.2439e-04, 1.4625e-03, 3.1554e-30,
       3.5123e-04, 1.8735e-30, 7.8845e-04, 1.7690e-03, 1.2929e-03,
       2.1746e-03, 8.3973e-04, 2.5884e-30, 3.4513e-30, 4.5910e-04,
       1.9435e-03, 1.5635e-03, 7.1270e-04, 1.5701e-03, 1.1246e-03,
       4.9304e-31, 1.8532e-03, 1.3312e-30, 1.7503e-30, 1.1833e-30,
       3.9443e-31, 1.7768e-03, 0.0000e+00, 1.4298e-30, 1.2833e-03,
       1.8168e-04, 8.9736e-04, 1.0689e-04, 8.6729e-04, 1.2095e-03,
       3.2856e-03, 1.4464e-03, 1.1586e-30, 5.8205e-04, 1.3748e-03,
       8.5144e-04, 1.8003e-03, 1.0894e-04, 2.2802e-03, 5.9165e-31])
Coordinates:
  * op       (op) int32 2456 1932 2635 2636 2802 ... 1486 1555 1303 1361 2467

In [90]:
dr1.coords['lat'] = ('op',lat_list_1)
dr1.coords['lon'] = ('op',lon_list_1)

In [91]:
dr1

<xarray.DataArray (op: 1000)>
array([1.1505e-03, 1.1251e-03, 5.8906e-04, 3.4773e-04, 1.4673e-03,
       7.4942e-30, 3.1061e-30, 1.5284e-30, 7.2484e-05, 3.0413e-03,
       2.2469e-03, 1.6008e-03, 8.4195e-04, 9.3457e-04, 1.6658e-03,
       2.2757e-03, 1.2421e-03, 1.1154e-03, 2.9499e-03, 0.0000e+00,
       2.6180e-03, 4.3387e-30, 1.3876e-03, 1.6008e-03, 1.3124e-03,
       0.0000e+00, 1.1152e-04, 3.8703e-30, 0.0000e+00, 1.2548e-03,
       5.1029e-30, 3.0634e-03, 1.8195e-03, 1.4681e-03, 0.0000e+00,
       7.8886e-30, 1.5540e-03, 0.0000e+00, 0.0000e+00, 1.1833e-30,
       5.9257e-04, 6.4095e-31, 7.7866e-04, 7.0534e-04, 1.5777e-28,
       3.2147e-04, 3.3639e-03, 5.5307e-06, 1.2819e-29, 4.4373e-31,
       1.8800e-03, 6.2047e-03, 1.2353e-03, 1.3698e-03, 7.9093e-04,
       5.8918e-30, 2.2017e-04, 0.0000e+00, 9.0019e-04, 0.0000e+00,
       1.0958e-03, 2.5144e-03, 8.4534e-04, 4.8364e-04, 3.7865e-29,
       2.5877e-03, 1.4606e-03, 4.0676e-30, 7.7055e-04, 4.5606e-30,
       1.4913e-03, 5.8467e-03, 0.0000e+00, 5.0901e-04, 0.0000e+00,
       2.8511e-03, 8.9923e-04, 0.0000e+00, 4.4236e-03, 0.0000e+00,
       3.5745e-30, 3.1517e-04, 4.7386e-03, 1.6008e-03, 1.3651e-03,
       8.7268e-30, 2.2642e-03, 0.0000e+00, 9.7173e-04, 1.8242e-30,
       0.0000e+00, 1.6008e-03, 3.7224e-30, 1.4139e-03, 7.6582e-05,
       4.3634e-30, 1.5493e-03, 0.0000e+00, 0.0000e+00, 0.0000e+00,
...
       9.1390e-04, 7.6072e-04, 5.7657e-04, 3.2137e-05, 4.0901e-03,
       4.2882e-03, 7.5924e-04, 5.6638e-04, 0.0000e+00, 0.0000e+00,
       1.0365e-04, 2.3511e-04, 2.5141e-04, 3.4460e-04, 0.0000e+00,
       0.0000e+00, 1.5716e-03, 4.9239e-04, 4.6480e-04, 0.0000e+00,
       4.3141e-30, 0.0000e+00, 7.6774e-04, 1.3805e-30, 3.4143e-04,
       1.1549e-03, 7.7693e-04, 9.9372e-29, 0.0000e+00, 1.8242e-30,
       4.2131e-03, 1.7208e-03, 1.9722e-30, 4.8817e-03, 1.2552e-03,
       0.0000e+00, 1.4970e-03, 7.9389e-04, 2.0105e-03, 0.0000e+00,
       0.0000e+00, 1.3381e-03, 6.4833e-04, 1.4774e-03, 1.9722e-31,
       1.5777e-30, 5.8643e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       3.1554e-30, 2.7185e-03, 9.2194e-04, 2.1225e-03, 2.7728e-04,
       7.8886e-31, 1.7061e-03, 5.2439e-04, 1.4625e-03, 3.1554e-30,
       3.5123e-04, 1.8735e-30, 7.8845e-04, 1.7690e-03, 1.2929e-03,
       2.1746e-03, 8.3973e-04, 2.5884e-30, 3.4513e-30, 4.5910e-04,
       1.9435e-03, 1.5635e-03, 7.1270e-04, 1.5701e-03, 1.1246e-03,
       4.9304e-31, 1.8532e-03, 1.3312e-30, 1.7503e-30, 1.1833e-30,
       3.9443e-31, 1.7768e-03, 0.0000e+00, 1.4298e-30, 1.2833e-03,
       1.8168e-04, 8.9736e-04, 1.0689e-04, 8.6729e-04, 1.2095e-03,
       3.2856e-03, 1.4464e-03, 1.1586e-30, 5.8205e-04, 1.3748e-03,
       8.5144e-04, 1.8003e-03, 1.0894e-04, 2.2802e-03, 5.9165e-31])
Coordinates:
  * op       (op) int32 2456 1932 2635 2636 2802 ... 1486 1555 1303 1361 2467
    lat      (op) float64 70.5 71.5 69.25 69.5 70.75 ... 74.75 73.75 74.25 73.25
    lon      (op) float64 24.0 22.5 24.5 24.5 25.0 ... 21.25 20.25 20.5 24.0

In [92]:
dr2 = xr.DataArray(beta_ov, dims=("op"),coords={"op":loc2.reshape(-1),
                                                "lat":("op",lat_list_2),"lon":("op",lon_list_2)})

In [95]:
op_ds = xr.Dataset({"op_algo": dr1})
ana_ds = xr.Dataset({"op_analysis": dr1})

In [97]:
import cartopy.crs as ccrs
import matplotlib as mpl
import matplotlib.pyplot as plt

In [100]:
ax = plt.axes(projection=ccrs.PlateCarree(78,24))
ax.set_global()
ax.coastlines()
plt.contourf(lon_list_1, lat_list_1, beta_op)

AttributeError: 'int' object has no attribute 'semimajor_axis'